#!/bin/sh

set -e                                    # exit execution if a command fails
set -a                                    # set marking all created and all modified variables for export
[ ! -f ./.env ] || . ./.env               # load environment variables
set +a                                    # unset marking variables for export

__ARG=$1

__PRODUCTION="prod"
__BUILD_DOCKER_IMAGE="build:image"
__START_DOCKER_IMAGE="start:image"
__STOP_DOCKER_IMAGE="stop:image"
__BUILD_CLI_BIN="build:cli"
__CLEAN_CLI_MAKE_BUILD="clean:cli"
__EXECUTE_CLI_BIN="exec:cli"
__START_UI_SERVER="exec:ui"
__START_AGENT_SERVER="exec:agent"
__START_SLACK_SERVER="exec:slack"


if [ "$__ARG" = "$__PRODUCTION" ]; then
    shift
    export CURRENT_ENV="production"
    supervisord
fi

if [ "$__ARG" = "$__BUILD_DOCKER_IMAGE" ]; then
    shift
    docker build -t "$@" hiramlabs/sortes .
fi

if [ "$__ARG" = "$__START_DOCKER_IMAGE" ]; then
    shift
    docker run --name sortes -d "$@" hiramlabs/sortes
fi

if [ "$__ARG" = "$__STOP_DOCKER_IMAGE" ]; then
    shift
    docker stop "$@" sortes
fi

if [ "$__ARG" = "$__BUILD_CLI_BIN" ]; then
    shift
    make -C ./cli
fi

if [ "$__ARG" = "$__CLEAN_CLI_MAKE_BUILD" ]; then
    shift
    make -C ./cli clean
fi

if [ "$__ARG" = "$__EXECUTE_CLI_BIN" ]; then
    shift
    ./cli/bin/${APP_NAME} "$@"
fi

if [ "$__ARG" = "$__START_UI_SERVER" ]; then
    shift
    if [ "$CURRENT_ENV" = "development" ]; then
        php -S "${LOCALHOST}":"${UI_DEV_PORT}" -t ./ui
    fi

    if [ "$CURRENT_ENV" = "test" ]; then
        echo "No Tests Defined"
    fi
fi

if [ "$__ARG" = "$__START_AGENT_SERVER" ]; then
    shift
    if [ "$CURRENT_ENV" = "development" ]; then
        uvicorn agent.api.main:app --host "${LOCALHOST}" --port "${AGENT_API_DEV_PORT}" --reload --reload-dir ./agent --log-level info --lifespan off
    fi

    if [ "$CURRENT_ENV" = "test" ]; then
        echo "No Tests Defined"
    fi
fi

if [ "$__ARG" = "$__START_SLACK_SERVER" ]; then
    shift
    if [ "$CURRENT_ENV" = "development" ]; then
        # ngrok may be needed for this https://api.slack.com/start/building/bolt-python#ngrok
        uvicorn slack.main:bot --host "${LOCALHOST}" --port "${SLACK_API_DEV_PORT}" --reload --reload-dir ./slack --log-level info --lifespan off
    fi

    if [ "$CURRENT_ENV" = "test" ]; then
        echo "No Tests Defined"
    fi
fi
